### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by hdduytran** [Beaglefoot/awk-language-server#62]
```log
Error: Connection got disposed.
    at Object.dispose (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/connection.js:1044:27)
    at Object.dispose (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-languageclient/lib/common/client.js:73:35)
    at LanguageClient.handleConnectionClosed (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-languageclient/lib/common/client.js:2424:42)
    at LanguageClient.handleConnectionClosed (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-languageclient/lib/node/main.js:155:15)
    at closeHandler (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-languageclient/lib/common/client.js:2411:18)
    at CallbackList.invoke (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at closeHandler (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/connection.js:256:26)
    at CallbackList.invoke (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/events.js:55:39)
    at Emitter.fire (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/events.js:117:36)
    at IPCMessageReader.fireClose (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/common/messageReader.js:40:27)
    at ChildProcess.<anonymous> (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/vscode-jsonrpc/lib/node/main.js:33:45)
    at ChildProcess.emit (node:events:525:35)
    at maybeClose (node:internal/child_process:1091:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:513:28)
    at Pipe.<anonymous> (node:net:322:12)
node:internal/url:185
  constructor(init = undefined) {
             ^

RangeError: Maximum call stack size exceeded
    at new URLSearchParams (node:internal/url:185:14)
    at URL.onParseComplete (node:internal/url:559:26)
    at new URL (node:internal/url:646:5)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:24:17)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)
    at getAwkFilesInDir (/home/itdev/.vscode-server/extensions/beaglefoot.awk-ide-vscode-0.10.3/node_modules/awk-language-server/out/io.js:37:28)

Node.js v18.15.0
[Error - 11:48:30 AM] Connection to server got closed. Server will not be restarted.
```

**Comment by Beaglefoot** [comment]
Do you run this with vscode?

**Comment by hdduytran** [comment]
Yes, I run it with vscode. It worked two months before. It's still working on windows 11 but not on Ubuntu

**Comment by anoduck** [comment]
If it matters, I would like to report I have been experiencing the same issue on OpenBSD with Emacs LSP-Mode. A little different from running it on Ubuntu with VS Code. 

I have tried to mitigate the issue by increasing the stack size of node, but this has had no effect.

```bash
/usr/local/bin/node --stack-size=16384 --max-old-space-size=16384 /usr/local/lib/node_modules/awk-language-server/out/cli.js
```
